blog/urls.py
from django.urls import path
from . import views


app_name= 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail')

]

contact/urls.py
from django.urls import path
from . import views


app_name= 'contact'

urlpatterns = [
    path('', views.contact_us, name='contact_us'),

]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('ai/', include('open_ai.urls')),
    path('api/', include('web_api.urls')),


    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views


app_name= 'portfolio'

urlpatterns = [
    path('', views.home, name='new_home'),
    path('old', views.old_home, name='home'),
    path('projects/',views.projects, name='projects_detail')

]

portfolio/models.py
from distutils.command.upload import upload
from django.db import models


# Create your models here.

class Skill(models.Model):
    rank = models.IntegerField(unique=True)
    heading = models.BooleanField(default=True)
    skill_name = models.CharField(max_length=100)
    def __str__(self):
        return self.skill_name

class Project(models.Model):
    rank = models.IntegerField(default=1)
    title = models.CharField(max_length=100)
    skills = models.ManyToManyField(Skill,blank=True)
    description = models.TextField()
    heading = models.BooleanField(default=True)
    url = models.URLField(blank=True)
    def __str__(self):
        return self.title

class ProjectImage(models.Model):
    projects = models.ForeignKey(Project, related_name='images',on_delete=models.CASCADE)
    rank = models.IntegerField(unique=True)
    heading = models.BooleanField(default=True)
    image = models.ImageField(upload_to=f'project_images/', blank=True, null=True,default='project_images/default_project.jpg')
    def __str__(self):
        return self.projects.title
class ProjectResponsebility(models.Model):
    property = models.ForeignKey(Project, related_name='responsebility',on_delete=models.CASCADE)
    rank = models.IntegerField(unique=True)
    heading = models.BooleanField(default=True)
    response = models.TextField()

portfolio/views.py
from django.shortcuts import render, redirect
from .models import Project,ProjectImage
from contact.models import SendMail
from django.core.mail import send_mail
from django.contrib import messages

msg = '''[<|message|>]

Hi <|NAME|>,

Thanks so much for writting us.

I just wanted to let you know that I'm looking into it and will get back to you before the end of week with an answer.

If you need me to get back to you sooner, please let me know!

Best Regards,
Gaurav Shankar Kumar
'''


# Create your views here.
def home(request):
    context = {}
    all_projects = Project.objects.filter(heading=True)
    all_projects_images = ProjectImage.objects.all()
    context['all_projects'] = all_projects
    context['all_projects_images'] = all_projects_images
    if request.POST:
        user_name = request.POST.get('user_name')
        message = request.POST.get('user_message')
        _from = 'heavycoder.in@gmail.com'
        useremail = request.POST.get('user_email')
        mail_data = SendMail(subject=user_name, message=message, useremail=useremail)
        mail_data.save()
        msgm=msg.replace("<|message|>", message)
        msgu=msgm.replace("<|NAME|>", user_name)
        send_mail(
            'HeavyCoder',
            msgu,
            _from,
            [useremail,'gauravshankarkumar@gmail.com'],
            fail_silently=False,
        )
        context['mail_success'] = True
        messages.success(request,f'Your Email Sent Successfully!')
        return redirect ('portfolio:new_home')
    
    return render (request,'portfolio/index.html',context)

def old_home(request):
    return render (request,'portfolio/home.html')
    # return render (request,'portfolio/components.html')


def projects(request):
    projects = Project.objects.all()
    return render (request,'portfolio/projects.html', {'projects':projects})

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />

  <link rel="stylesheet" href="{% static " portfolio/custom.css" %}">

  {% block css %}{% endblock css %}
  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet" />

  <link rel="icon" type="image/png" href="{% static " portfolio/logo.jpg" %}" />

  <title>Gaurav Shankar Kumar</title>
</head>

<body>
  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'portfolio:home' %}">
        <img src="{% static " portfolio/logo.jpg" %}" width="30" height="30" class="d-inline-block align-top"
          alt="Gaurav's Logo" />
        <span>Gaurav Shankar Kumar</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">


          <li class="nav-item">
            <a class="nav-link" href="{% url 'portfolio:projects_detail' %}">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link"
              href="https://drive.google.com/file/d/1RJI3kTGb9PZ1AUkCyO3DEMjCP_hllU_q/view?usp=sharing"
              target="_blank">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/gauravshankarkumar/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/gauravshankarkumar" target="_blank">GitHub</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.facebook.com/gauravshankarkumar" target="_blank">Facebook</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.instagram.com/gauravshankarkumar/" target="_blank">Instagram</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/gauravshankarkr" target="_blank">Twitter</a>
          </li>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blog</a>
          </li>
          <li>
            <a role="button" href="{% url 'contact:contact_us' %}" class="btn btn-warning">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">{% block content %}{% endblock content %}</div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
  <script>
    $('img[src*="/media/"]').each(function() {
      var src = $(this).attr('src');
      src = src.replace('/media/', '/static/');
      $(this).attr('src', src);
    });
  </script>    
</body>

</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %} {% load static %} {% block content %}

<!-- slide photo settings -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>

  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static " portfolio/gsk.jpg" %}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static " portfolio/gsk1.jpg" %}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static " portfolio/gsk2.jpg" %}" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static " portfolio/gsk3.jpg" %}" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!-- end of slide  -->
<!-- home text self -->
<div>
  <div>
    <h1 id="hometext" class="font-weight-bold" style="text-align:justify; font-size:25px ; margin-top:20px">
      <a href=""> Gaurav Shankar Kumar </a> <span style="font-size: 25px;"> is Certified in Full Stack Web development
        with Django - React Stack.
        Knowledge of SCM with programmatic experience. Strong analytical and problem-solving skills with experience on
        projects.
        Focused on building scalable applications with best Industrial practices.😊</span>
    </h1>
    <br>
    <br>
    <!-- skills sections -->
    <div>
      <h2 id="hometext" class="font-weight-bold; font-size:30px">
        <span style="float:left">My Skill</span>
        <span style="float:right;"> <a href="{% url 'portfolio:projects_detail' %}"> <span
              style="font-weight: lighter;font-size:10px">Click for 👉🏼</span> My Projects </a> </span>

      </h2>
    </div>
    <br />
    <br />
    <br />
    <div>
      <div class="progress-bar progress-bar-striped progress-bar-animated"
        style="margin-top: 10px; width:60%; height:30px">Python</div>
      <div class="progress-bar bg-success progress-bar-striped progress-bar-animated"
        style="margin-top: 10px; width:70%; height:30px">Django</div>
      <div class="progress-bar bg-info progress-bar-striped progress-bar-animated"
        style="margin-top: 10px; width:60%; height:30px">Django Rest Frame Work</div>
      <div class="progress-bar bg-warning progress-bar-striped progress-bar-animated"
        style="margin-top: 10px; width:50%; height:30px">JavaScript</div>
      <div class="progress-bar bg-danger progress-bar-striped progress-bar-animated"
        style="margin-top: 10px; width:30%; height:30px">React</div>
      <div class="progress-bar bg-secondary progress-bar-striped progress-bar-animated"
        style="margin-top: 10px; width:70%; height:30px">HTML & CSS</div>
      <div class="progress-bar bg-dark progress-bar-striped progress-bar-animated"
        style="margin-top: 10px; width:80%; height:30px">GitHub</div>
    </div>

  </div>
</div>
<hr />
<hr />

</div>

{% endblock content %}

portfolio/templates/portfolio/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% include 'portfolio/components/head.html' %}
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">
    {% comment %} <a href="components.html" class="btn btn-primary btn-component" data-spy="affix" data-offset-top="600"><i class="ti-shift-left-alt"></i> Components</a> {% endcomment %}
    
    {% include 'portfolio/components/header.html' %}
    {% include 'portfolio/components/nav.html' %}
    {% include 'portfolio/components/home.html' %}
    {% include 'portfolio/section/resume.html' %}
    {% comment %} {% include 'portfolio/section/center1.html' %} {% endcomment %}
    {% comment %} {% include 'portfolio/section/my_service.html' %} {% endcomment %}
    {% comment %} {% include 'portfolio/section/pack_pricing.html' %} {% endcomment %}
    {% comment %} {% include 'portfolio/section/center2.html' %} {% endcomment %}
    {% include 'portfolio/section/portfolio.html' %}
    {% include 'portfolio/section/blog_news.html' %}
    {% include 'portfolio/components/contact_us.html' %}
    {% include 'portfolio/components/footer.html' %}
	{% include 'portfolio/components/scripts.html' %}
    {% if messages %}
    {% for message in messages %}
    <script>
        alert ("{{message}}");
    </script>
    
    {% endfor %}
    {% endif %}

</body>
</html>

portfolio/templates/portfolio/projects.html
{% extends "portfolio/base.html" %} {% load static %} {% block content %}

<h2 class="mt-5">Portfolio</h2>
<hr />
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">
    {% if project.url %}
    <a href="{{ project.url }}" target="_blank">
      <img src="{{ project.image }}" width="400" height="400" class="img-fluid mb-2" />
    </a>
    {% else %}

    <img src="{{ project.image }}" width="400" height="400" class="img-fluid mb-2" />
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>
  </div>
  {% endfor %}
</div>

{% endblock content %}